--------------------------------------------------------
--  File created - Th? N?m-tháng 6-27-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

CREATE TABLE "HAN_SPRING_REST"."LOCATIONS"
(	"CODE" VARCHAR2(10 CHAR),
     "CITY_NAME" VARCHAR2(128 CHAR),
     "COUNTRY_CODE" VARCHAR2(2 CHAR),
     "COUNTRY_NAME" VARCHAR2(64 CHAR),
     "ENABLED" NUMBER(1,0),
     "REGION_NAME" VARCHAR2(128 CHAR),
     "TRASHED" NUMBER(1,0)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WEATHER_REALTIME
--------------------------------------------------------

CREATE TABLE "HAN_SPRING_REST"."WEATHER_REALTIME"
(	"LOCATION_CODE" VARCHAR2(10 CHAR),
     "HUMIDITY" NUMBER(10,0),
     "LAST_UPDATED" TIMESTAMP (6),
     "PRECIPITATION" NUMBER(10,0),
     "STATUS" VARCHAR2(50 CHAR),
     "TEMPERATURE" NUMBER(10,0),
     "WIND_SPEED" NUMBER(10,0)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
    NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
            BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS" ;
REM INSERTING into HAN_SPRING_REST.LOCATIONS
SET DEFINE OFF;
Insert into HAN_SPRING_REST.LOCATIONS (CODE,CITY_NAME,COUNTRY_CODE,COUNTRY_NAME,ENABLED,REGION_NAME,TRASHED) values ('DELHI_IN','Delhi','IN','India',1,'Delhi',0);
Insert into HAN_SPRING_REST.LOCATIONS (CODE,CITY_NAME,COUNTRY_CODE,COUNTRY_NAME,ENABLED,REGION_NAME,TRASHED) values ('LACA_US','Los Angeles','US','United State of America',1,'California',0);
Insert into HAN_SPRING_REST.LOCATIONS (CODE,CITY_NAME,COUNTRY_CODE,COUNTRY_NAME,ENABLED,REGION_NAME,TRASHED) values ('NYC_USA','New York City','US','United State of America',1,'New York',0);
REM INSERTING into HAN_SPRING_REST.WEATHER_REALTIME
SET DEFINE OFF;
Insert into HAN_SPRING_REST.WEATHER_REALTIME (LOCATION_CODE,HUMIDITY,LAST_UPDATED,PRECIPITATION,STATUS,TEMPERATURE,WIND_SPEED) values ('NYC_USA',20,to_timestamp('27-JUN-24 02.11.10.554790000 PM','DD-MON-RR HH.MI.SSXFF AM'),3,'Sunny',30,2);
Insert into HAN_SPRING_REST.WEATHER_REALTIME (LOCATION_CODE,HUMIDITY,LAST_UPDATED,PRECIPITATION,STATUS,TEMPERATURE,WIND_SPEED) values ('DELHI_IN',200,to_timestamp('27-JUN-24 02.21.02.453298000 PM','DD-MON-RR HH.MI.SSXFF AM'),7,'Rainy',60,5);
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" MODIFY ("CITY_NAME" NOT NULL ENABLE);
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" ADD CHECK (enabled in (0,1)) ENABLE;
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" ADD CHECK (trashed in (0,1)) ENABLE;
ALTER TABLE "HAN_SPRING_REST"."LOCATIONS" ADD PRIMARY KEY ("CODE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WEATHER_REALTIME
--------------------------------------------------------

ALTER TABLE "HAN_SPRING_REST"."WEATHER_REALTIME" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
ALTER TABLE "HAN_SPRING_REST"."WEATHER_REALTIME" ADD PRIMARY KEY ("LOCATION_CODE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
        BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WEATHER_REALTIME
--------------------------------------------------------

ALTER TABLE "HAN_SPRING_REST"."WEATHER_REALTIME" ADD CONSTRAINT "FKHON6DBBPH4HLFFSY78RO0DFWK" FOREIGN KEY ("LOCATION_CODE")
    REFERENCES "HAN_SPRING_REST"."LOCATIONS" ("CODE") ENABLE;